(() => {
  'use strict';
  const cfg=window.ADSCOPE_CONFIG;
  const client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const app=document.getElementById('portalApp');const toastRoot=document.getElementById('toastRoot');
  let session=null,profile=null,events=[];
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:cfg.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const time=v=>new Intl.DateTimeFormat('en-GB',{timeZone:cfg.timezone,hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(v));
  function toast(m){const n=document.createElement('div');n.className='toast';n.textContent=m;toastRoot.append(n);setTimeout(()=>n.remove(),3500)}
  function friendlyError(error){const raw=String(error?.message||error||'Something went wrong.');if(/not linked to an employee/i.test(raw))return'This account is not linked to an employee profile.';if(/attendance is not required/i.test(raw))return'Your account does not require daily attendance.';if(/portal access is disabled/i.test(raw))return'Attendance portal access is not enabled for this account.';if(/invalid login credentials/i.test(raw))return'The email or password is incorrect.';if(/email not confirmed/i.test(raw))return'Please confirm your email address before signing in.';if(/origin not allowed/i.test(raw))return'This attendance page is not authorized yet. Contact the system administrator.';if(/permission denied/i.test(raw))return'Your account does not have permission to use this attendance action.';return raw.replaceAll('_',' ')}
  function loading(){app.innerHTML='<div class="loading"><div><div class="spinner"></div>Loading attendance portal…</div></div>'}
  function login(message=''){app.innerHTML=`<section class="page"><div class="card"><div class="brand"><div class="mark">A</div><div><div class="title">Adscope Attendance</div><div class="sub">Secure employee portal</div></div></div><h1>Sign in</h1><p>Use your assigned Adscope account.</p>${message?`<div class="notice">${esc(message)}</div>`:''}<form id="login"><label class="field"><span>Email</span><input name="email" type="email" required></label><label class="field"><span>Password</span><input name="password" type="password" required></label><button class="primary" type="submit">Sign in</button></form><button class="link" id="forgot">Forgot password?</button></div></section>`;
    document.getElementById('login').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const{error}=await client.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error)login(friendlyError(error))};
    document.getElementById('forgot').onclick=async()=>{const email=prompt('Enter your email address');if(!email)return;const redirectTo=new URL('/attendance/',location.origin).href;const{error}=await client.auth.resetPasswordForEmail(email,{redirectTo});toast(error?friendlyError(error):'Password reset email sent.')};
  }
  async function load(){
    const p=await client.rpc('get_my_attendance_profile');if(p.error)throw p.error;profile=p.data;
    const employeeId=profile.employee_id||profile.id||profile.employee?.id;
    const q=await client.from('attendance_events').select('event_type,occurred_at').eq('employee_id',employeeId).eq('attendance_date',localDate()).order('occurred_at');if(q.error)throw q.error;events=q.data||[];
  }
  function currentState(){const last=events.at(-1)?.event_type;if(events.some(e=>e.event_type==='CHECK_OUT'))return'done';if(last==='BREAK_START')return'break';if(events.some(e=>e.event_type==='CHECK_IN'))return'working';return'not-in'}
  function allowed(){return{'not-in':['CHECK_IN'],working:['BREAK_START','CHECK_OUT'],break:['BREAK_END'],done:[]}[currentState()]}
  function label(type){return{CHECK_IN:'Check In',BREAK_START:'Start Break',BREAK_END:'End Break',CHECK_OUT:'Check Out'}[type]}
  function render(){const s=currentState();const employeeName=profile.full_name||profile.employee_name||profile.employee?.full_name||'Employee';const shiftName=profile.shift_name||profile.shift?.name||'Assigned shift';app.innerHTML=`<section class="page"><div class="card"><div class="header"><div class="brand"><div class="mark">A</div><div><div class="title">Attendance</div><div class="sub">${esc(employeeName)}</div></div></div><button class="link" id="logout">Log out</button></div><div class="status-card"><div class="status">${esc(s.replace('-',' '))}</div><div class="clock" id="clock"></div></div><div class="details"><div class="detail"><span>Date</span><strong>${esc(localDate())}</strong></div><div class="detail"><span>Shift</span><strong>${esc(shiftName)}</strong></div></div><div class="stack">${allowed().map(t=>`<button class="${t==='CHECK_OUT'?'danger':t==='CHECK_IN'?'primary':'secondary'}" data-action="${t}">${label(t)}</button>`).join('')}${allowed().length?'':'<div class="notice success">Today’s attendance sequence is complete.</div>'}</div><div class="events"><strong>Today’s events</strong>${events.map(e=>`<div class="event"><span>${esc(label(e.event_type))}</span><strong>${esc(time(e.occurred_at))}</strong></div>`).join('')||'<p>No attendance events yet.</p>'}</div></div></section>`;
    document.getElementById('logout').onclick=()=>client.auth.signOut();app.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>record(b.dataset.action,b));
    const updateClock=()=>{const el=document.getElementById('clock');if(el)el.textContent=new Intl.DateTimeFormat('en-GB',{timeZone:cfg.timezone,dateStyle:'full',timeStyle:'medium'}).format(new Date())};updateClock();setInterval(updateClock,1000);
  }
  async function record(type,button){button.disabled=true;button.textContent='Saving…';const{data,error}=await client.functions.invoke('attendance-event',{body:{type,idempotencyKey:crypto.randomUUID()}});if(error){button.disabled=false;button.textContent=label(type);return toast(friendlyError(error))}if(data?.error){button.disabled=false;button.textContent=label(type);return toast(friendlyError(data.error))}toast(`${label(type)} recorded.`);await load();render()}
  async function boot(){loading();const{data:{session:s}}=await client.auth.getSession();session=s;if(!s)return login();try{await load();render()}catch(e){app.innerHTML=`<section class="page"><div class="card"><div class="brand"><div class="mark">A</div><div><div class="title">Attendance unavailable</div><div class="sub">Account signed in</div></div></div><div class="notice">${esc(friendlyError(e))}</div><p>This account may be an administrator, exempt from daily attendance, inactive, or not enabled for the employee portal.</p><button class="ghost" id="logout">Log out</button></div></section>`;document.getElementById('logout').onclick=()=>client.auth.signOut()}}
  let booting=null;
  function bootOnce(){if(booting)return booting;booting=boot().finally(()=>{booting=null});return booting}
  client.auth.onAuthStateChange((event,s)=>{window.setTimeout(()=>{const previousUserId=session?.user?.id;session=s;if(!s||event==='SIGNED_OUT')return login();if(previousUserId===s.user?.id&&profile)return;bootOnce().catch(error=>{if(profile)return toast(friendlyError(error));login(friendlyError(error))})},0)});bootOnce().catch(error=>login(friendlyError(error)));
})();
